---
- name: Create a new user
  user:
    name: "{{ new_user }}"
    shell: /bin/bash
    groups: sudo
    append: yes
    create_home: yes

- name: Set authorized_keys directory
  file:
    path: "/home/{{ new_user }}/.ssh"
    state: directory
    mode: '0700'
    owner: "{{ new_user }}"
    group: "{{ new_user }}"
