cloudflared_tunnel_token: "CLOUDFLARE_TUNNEL_TOKEN_HERE"
bitwarden_client_id: "BITWARDEN_CLIENT_ID_HERE"
bitwarden_client_secret: "BITWARDEN_CLIENT_SECRET_HERE"
bitwarden_password: "BITWARDEN_PASSWORD_HERE"
veracrypt_password: "VERACRYPT_PASSWORD_HERE"
vault_paperless_samba_password: "PAPERLESS_SAMBA_PASSWORD_HERE"
vault_proxmox_user: "PROXMOX_USER_HERE"
vault_proxmox_password: "PROXMOX_PASSWORD_HERE"
vault_mosquitto_user: "MOSQUITTO_USER_HERE"
vault_mosquitto_password: "MOSQUITTO_PASSWORD_HERE"